services:
  transit-display:
    build:
      context: .
      dockerfile: Dockerfile
    image: transit-display
    container_name: transit-display
    restart: unless-stopped
    volumes:
      - /dev/fb0:/dev/fb0:rw  # framebuffer